name: Simple CI job

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: |
          echo "Hello World!"
          echo "Adjustment - date added"
          current_date_time=$(date)
          echo "Current date and time: $current_date_time"